name: Build and Push Docker Image

on:
    push:
        branches: [staging]
    pull_request:
        branches: [staging]

jobs:
    build-and-push:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: angysquirrel/morse-front
                  tags: |
                      type=ref,event=branch
                      type=ref,event=pr
                      type=raw,value=latest,enable={{is_default_branch}}
                      type=sha,format=long # Ajout du tag avec le SHA du commit

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  build-args: |
                      BUILDKIT_INLINE_CACHE=1

            - name: Clean up Docker images on self-hosted runner
              if: always()
              run: |
                  echo "Cleaning up Docker system on runner..."
                  docker system prune -af || true # Supprime les images, conteneurs, volumes et réseaux non utilisés
                  docker volume prune -f || true # S'assure que les volumes sont aussi nettoyés

    pull-image-and-deploy:
        runs-on: self-hosted
        needs: build-and-push

        steps:
            - name: Deploy to remote server via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_PRIVATE_KEY }}
                  script: |
                      IMAGE_TAG="angysquirrel/morse-front:${{ github.sha }}" 

                      echo "Pulling Docker image: $IMAGE_TAG"
                      docker pull $IMAGE_TAG || { echo "Failed to pull image $IMAGE_TAG"; exit 1; }

                      echo "Stopping and removing existing container 'morse-front' (if any)"
                      docker stop morse-front || true
                      docker rm morse-front || true

                      echo "Running new Docker container 'morse-front'"
                      docker run -d \
                          --name morse-front \
                          -p 85:80 \
                          --restart unless-stopped \
                          $IMAGE_TAG || { echo "Failed to start container 'morse-front'"; exit 1; }

                      echo "Waiting for container to stabilize..."
                      sleep 10 

                      echo "Displaying last 20 lines of container logs for initial startup check:"
                      docker logs morse-front | tail -n 20

                      echo "Verifying container status..."
                      if docker ps -q -f name=morse-front; then
                          echo "Container 'morse-front' is running successfully."
                          # Optionnel : Ajoutez un health check HTTP si votre application a une route de santé
                          # curl -f http://localhost:85/health || { echo "Health check failed!"; exit 1; }
                      else
                          echo "Container 'morse-front' failed to start."
                          echo "Full logs for 'morse-front':"
                          docker logs morse-front # Affiche les logs complets en cas d'échec
                          exit 1
                      fi

            - name: Clean up old Docker images on remote server
              if: always()
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VPS_HOST }}
                  username: ${{ secrets.VPS_USERNAME }}
                  key: ${{ secrets.VPS_PRIVATE_KEY }}
                  script: |
                      echo "Cleaning up old Docker images on remote server..."
                      # Supprime les images non utilisées de plus de 24 heures. Ajustez la durée si nécessaire.
                      docker image prune -af --filter "until=24h" || true
                      # Nettoie également les volumes et réseaux non utilisés sur le système
                      docker system prune -f || true
